# Generated by Django 5.1.4 on 2025-01-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.answer'),
            preserve_default=False,
        ),
    ]
